/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ismaili
 */
public class RoomAllocated extends javax.swing.JFrame {

    /**
     * Creates new form RoomAllocated
     */
    public RoomAllocated() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        admno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        roomass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Admission Number");

        admno.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        admno.setText("jTextField1");
        admno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admnoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("Block & Room Assigned");

        roomass.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        roomass.setText("jTextField2");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton2.setText("Help");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setText("Enter Admission No and Press search for room");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(admno, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(roomass))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(search)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(admno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(roomass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(search)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        admno.setText(LogIN.admno.getText());
        admno.setEditable(false);
        roomass.setText("");
        roomass.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setText("Room Allocation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admnoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(RoomAllocated.this,"Contact SYS ADM\n ismizo@live.com","HELP",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

        String admission_no = admno.getText();
        String roomy=roomass.getText();
        
        
        if(roomy.length()>1){
            roomass.setText("");
        }
        
        
    try {
    String host = "jdbc:mysql://localhost:3306/javaprojects?zeroDateTimeBehavior=convertToNull";
    String uName ="admins";
    String uPass ="276438951";
    Connection con = DriverManager.getConnection(host,uName,uPass);    
    
    Statement stmt = con.createStatement();
    String SQL = "SELECT*FROM block1 where OCCUPANT_1='"+admission_no+"'OR OCCUPANT_2='"+admission_no+"'OR OCCUPANT_3='"+admission_no+"'OR OCCUPANT_4='"+admission_no+"'OR OCCUPANT_5='"+admission_no+"'OR OCCUPANT_6='"+admission_no+"'OR OCCUPANT_7='"+admission_no+"'OR OCCUPANT_8='"+admission_no+"'OR OCCUPANT_9='"+admission_no+"'OR OCCUPANT_10='"+admission_no+"'";
    ResultSet rs = stmt.executeQuery(SQL);
    
    if (rs.next()){
        int roomno=rs.getInt("ROOM_ID");
        String blockhui="BLOCK 1";
        roomass.setText(blockhui+" "+"ROOM "+Integer.toString(roomno));
        
    }
    else{
        rs.close();
        String SQL1 = "SELECT*FROM block2 where OCCUPANT_1='"+admission_no+"'OR OCCUPANT_2='"+admission_no+"'OR OCCUPANT_3='"+admission_no+"'OR OCCUPANT_4='"+admission_no+"'OR OCCUPANT_5='"+admission_no+"'OR OCCUPANT_6='"+admission_no+"'OR OCCUPANT_7='"+admission_no+"'OR OCCUPANT_8='"+admission_no+"'OR OCCUPANT_9='"+admission_no+"'OR OCCUPANT_10='"+admission_no+"'";
        ResultSet rs1 = stmt.executeQuery(SQL1);
        if (rs1.next()){
        int roomno=rs1.getInt("ROOM_ID");
        String block52="BLOCK 2";
        roomass.setText(block52+" "+"ROOM "+Integer.toString(roomno));
        
    }else{
        rs1.close();
        String SQL2 = "SELECT*FROM block3 where OCCUPANT_1='"+admission_no+"'OR OCCUPANT_2='"+admission_no+"'OR OCCUPANT_3='"+admission_no+"'OR OCCUPANT_4='"+admission_no+"'OR OCCUPANT_5='"+admission_no+"'OR OCCUPANT_6='"+admission_no+"'OR OCCUPANT_7='"+admission_no+"'OR OCCUPANT_8='"+admission_no+"'OR OCCUPANT_9='"+admission_no+"'OR OCCUPANT_10='"+admission_no+"'";
        ResultSet rs2 = stmt.executeQuery(SQL2);
        if (rs2.next()){
        int roomno=rs2.getInt("ROOM_ID");
        
        String block51="BLOCK 3";
        roomass.setText(block51+" "+"ROOM "+Integer.toString(roomno));
        }else{
            rs2.close();
        String SQL3 = "SELECT*FROM block4 where OCCUPANT_1='"+admission_no+"'OR OCCUPANT_2='"+admission_no+"'";
        ResultSet rs3 = stmt.executeQuery(SQL3);
        if (rs3.next()){
        int roomno=rs3.getInt("ROOM_ID");
        String blockp="BLOCK 4";
        roomass.setText(blockp+" "+"ROOM "+Integer.toString(roomno));
        }else{
           rs3.close();
        String SQL4 = "SELECT*FROM block5 where OCCUPANT_1='"+admission_no+"'OR OCCUPANT_2='"+admission_no+"'";
        ResultSet rs4 = stmt.executeQuery(SQL4);
        if (rs4.next()){
        int roomno=rs4.getInt("ROOM_ID");
        String blockt="BLOCK 5";
        String roomyno=Integer.toString(roomno);
        
        if(roomyno.endsWith("1")){
            roomyno = roomyno.substring(0, roomyno.length()-1);
            roomyno=(roomyno)+"A";
        }
        if(roomyno.endsWith("2")){
            roomyno = roomyno.substring(0, roomyno.length()-1);
            roomyno=roomyno+"B";
        }
        roomass.setText(blockt+" "+"ROOM "+roomyno);
        }else{
        rs4.close();
        String SQL5 = "SELECT*FROM block6 where OCCUPANT_1='"+admission_no+"'OR OCCUPANT_2='"+admission_no+"'";
        ResultSet rs5 = stmt.executeQuery(SQL5);
        if (rs5.next()){
        int roomno=rs5.getInt("ROOM_ID");
        String blocky="BLOCK 6";
        String roomyno=Integer.toString(roomno);
        
        if(roomyno.length()<2){
            roomyno="T"+roomyno;
        }
        roomass.setText( blocky+" "+"ROOM "+roomyno);
        }else{
            JOptionPane.showMessageDialog(RoomAllocated.this, "Not Found");
        }
            
            
        } 
            
            
            
        }
            
            
            
        
        
    }}}
   
        }
        catch (SQLException err){
            JOptionPane.showMessageDialog(this, err.getLocalizedMessage());
        }
        
        
              
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomAllocated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomAllocated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomAllocated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomAllocated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomAllocated().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField admno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField roomass;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
